name: Main

on: push

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Run TypeScript compiler
      run: tsc
    
    - name: Run Build
      run: npm run build
